### ISSUE TITLE
Dynlights+Fatty foods DL broken

### ISSUE THREAD

**Issue by SilearFlare** [Hirachosan/FattyFoodsAddon#1]
The latest download of fatty foods, which bundles together FFA and DynLights, does not actually have a working version of dynamic lighting. Tried downloading FFA+DL, only FFA works.
When downloading both mods separately (directly against what is said in the release) instead, both mods work properly.
Tested myself with both instances by holding a lit torch in a cave. 
FFA+DL = no light but fatty foods
FFA & DL separately = light and fatty foods

Seems pretty straightforward, there's an issue with the release.
Thanks in advance with any help on the subject.

**Comment by Hirachosan** [comment]
Nothing seems wrong with the FFA+DL pack, installing it separately makes for some incompatabilities, either you won't have Dynamic lights, or you won't have some functions from FFA (some new potion effects)  depending on your installation order.

Are you using any other addons in your instance? because I think you're also using deco, and installing deco after the pack

-edit- I've updated the forum post to include saying this mod goes after Deco

**Comment by SilearFlare** [comment]
Oh man, I didn't even know there were priorities problems when loading mods. Alright, thanks.
